spring.application.name=CrudSpringBootDemo

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/SpringCRUDDemo
spring.datasource.username=root
spring.datasource.password=Karthik@01

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080